// Auto-generated by cli/generate-types.ts

export type HerbsRecord = {
slug: string;
    name: string;
    nameScientific: string;
    overview: string;
    efficacy: string;
    tagSlugs: string[];
    content: string;
    updatedAt: Date;
    createdAt: Date;
  tags?: TagsRecord[];
  reports?: ReportsRecord[];
};
export type HerbStatesRecord = {
    slug: string;
    name: string;
};
export type ReportsRecord = {
slug: string;
    reportGroupSlug: string;
    summary: string;
    ingredients: string[];
    recipe: string[];
    content: string;
    updatedAt: Date;
    createdAt: Date;
  reportGroup?: ReportGroupsRecord;
  herbs?: HerbsRecord[];
  process?: ProcessesRecord;
  usageMethod?: UsageMethodsRecord;
};
export type ReportGroupsRecord = {
slug: string;
    description: string;
    combinedHerbs: {
        slug: string;
        herbStateSlug: string;
        herbPartSlug: string;
        description: string;
    }[];
    processSlug: string;
  process?: ProcessesRecord;
  herbs?: HerbsRecord[];
};
export type TagsRecord = {
    slug: string;
    name: string;
};
export type ProcessesRecord = {
    slug: string;
    name: string;
};
export type UsageMethodsRecord = {
    slug: string;
    name: string;
};

export type HerbsIndex_name = Record<string, string[]>;
export type ReportsIndex_slug = Record<string, string[]>;

export type HerbsMeta = Record<string, {
  "slug": string;
  "name": string;
  "overview": string;
  "herbState.name"?: any;
  "tags": TagsRecord[];
  "reports.slug"?: string[];
  "updatedAt": string;
}>;

export type ReportsMeta = Record<string, {
  "reportGroupSlug": string;
  "processSlug": any;
  "reportGroup.combinedHerbs.slug"?: string[];
  "process.name"?: string;
  "herbs.name"?: string[];
  "summary": string;
  "updatedAt": string;
}>;


export type HerbsRelation_tags = Record<string, string[]>;
export type HerbsRelation_reports = Record<string, string[]>;
export type ReportsRelation_reportGroup = Record<string, string>;
export type ReportsRelation_herbs = Record<string, string[]>;
export type ReportsRelation_process = Record<string, string>;
export type ReportsRelation_usageMethod = Record<string, string>;
export type ReportGroupsRelation_process = Record<string, string>;
export type ReportGroupsRelation_herbs = Record<string, string[]>;

