// Auto-generated by scripts/generate-types.ts

export type HerbsRecord = {
  slug: string;
  name: string;
  nameScientific: string;
  overview: string;
  efficacy: string;
  tagSlugs: string[];
  content: string;
  updatedAt: Date;
  createdAt: Date;
  tags?: TagsRecord[];
  reports?: ReportsRecord[];
};

export type HerbsIndex_name = Record<string, string[]>;

export type HerbsMeta = Record<
  string,
  {
    slug: any;
    name: any;
    "herbState.name": any;
    tags: any;
    "reports.slug": any;
    updatedAt: any;
  }
>;

export type HerbsRelation_tags = Record<string, string[]>;
export type HerbsRelation_reports = Record<string, string[]>;

export type HerbStatesRecord = {
  slug: string;
  name: string;
};

export type ReportsRecord = {
  slug: string;
  reportGroupSlug: string;
  summary: string;
  ingredients: string[];
  recipe: string[];
  content: string;
  updatedAt: Date;
  createdAt: Date;
  reportGroups?: ReportGroupsRecord;
  herbs?: HerbsRecord[];
  process?: ProcessesRecord;
  usageMethod?: UsageMethodsRecord;
};

export type ReportsIndex_slug = Record<string, string[]>;

export type ReportsMeta = Record<
  string,
  {
    reportGroupSlug: any;
    processSlug: any;
    "combinedHerbs.slug": any;
    "process.name": any;
    "herbs.name": any;
    updatedAt: any;
  }
>;

export type ReportsRelation_reportGroups = Record<string, string>;
export type ReportsRelation_herbs = Record<string, string[]>;
export type ReportsRelation_process = Record<string, string>;
export type ReportsRelation_usageMethod = Record<string, string>;

export type ReportGroupsRecord = {
  slug: string;
  combinedHerbs: {
    slug: string;
    herbStateSlug: string;
    herbPartSlug: string;
    description: string;
  }[];
  processSlug: string;
  processes?: ProcessesRecord;
  herbs?: HerbsRecord;
};

export type ReportGroupsRelation_processes = Record<string, string>;
export type ReportGroupsRelation_herbs = Record<string, string>;

export type TagsRecord = {
  slug: string;
  name: string;
};

export type ProcessesRecord = {
  slug: string;
  name: string;
};

export type UsageMethodsRecord = {
  slug: string;
  name: string;
};
