// Auto-generated by cli/generate-types.ts

export type HerbsRecord = {
slug: string;
    name: string;
    nameAliases: string[];
    nameScientific: string;
    compoundSlugs: string[];
    tagSlugs: string[];
    overview: string;
    efficacy: string;
    wiki: string;
    content: string;
    updatedAt: Date;
    createdAt: Date;
  compounds?: CompoundsRecord[];
  tags?: TagsRecord[];
  reports?: ReportsRecord[];
};
export type HerbStatesRecord = {
    slug: string;
    name: string;
};
export type HerbPartsRecord = {
    slug: string;
    name: string;
};
export type ReportsRecord = {
slug: string;
    reportGroupSlug: string;
    summary: string;
    ingredients: string[];
    recipe: string[];
    flavor: {
        bitterness: number;
        astringency: number;
        sweetness: number;
        sourness: number;
        spiciness: number;
        umami: number;
    };
    content: string;
    images: {
        imageUrl: string;
        caption: string;
        sortOrder: number;
    }[];
    updatedAt: Date;
    createdAt: Date;
  reportGroup?: ReportGroupsRecord;
  herbs?: HerbsRecord[];
  process?: ProcessesRecord;
  usageMethod?: UsageMethodsRecord;
};
export type ReportGroupsRecord = {
slug: string;
    description: string;
    combinedHerbs: {
        slug: string;
        herbStateSlug: string;
        herbPartSlug: string;
    }[];
    processSlug: string;
  process?: ProcessesRecord;
  herbs?: HerbsRecord[];
};
export type TagsRecord = {
    slug: string;
    name: string;
};
export type ProcessesRecord = {
    slug: string;
    name: string;
};
export type UsageMethodsRecord = {
    slug: string;
    name: string;
};
export type CompoundsRecord = {
    slug: string;
    name: string;
    description: string;
};

export type HerbsIndex_slug = Record<string, string[]>;
export type HerbsIndex_name = Record<string, string[]>;
export type HerbsIndex_tagSlugs = Record<string, string[]>;
export type HerbStatesIndex_slug = Record<string, string[]>;
export type HerbPartsIndex_slug = Record<string, string[]>;
export type ReportsIndex_slug = Record<string, string[]>;
export type ReportsIndex_reportGroupSlug = Record<string, string[]>;
export type ReportGroupsIndex_slug = Record<string, string[]>;

export type HerbsMeta = Record<string, {
  "slug": string;
  "name": string;
  "overview": string;
  "herbState.name"?: any;
  "tags": TagsRecord[];
  "reports.slug"?: string[];
  "updatedAt": string;
}>;

export type ReportsMeta = Record<string, {
  "reportGroupSlug": string;
  "processSlug": any;
  "reportGroup.combinedHerbs.slug"?: string[];
  "process.name"?: string;
  "herbs.name"?: string[];
  "summary": string;
  "updatedAt": string;
}>;


export type HerbsRelation_compounds = Record<string, string[]>;
export type HerbsRelation_tags = Record<string, string[]>;
export type HerbsRelation_reports = Record<string, string[]>;
export type ReportsRelation_reportGroup = Record<string, string>;
export type ReportsRelation_herbs = Record<string, string[]>;
export type ReportsRelation_process = Record<string, string>;
export type ReportsRelation_usageMethod = Record<string, string>;
export type ReportGroupsRelation_process = Record<string, string>;
export type ReportGroupsRelation_herbs = Record<string, string[]>;

